config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  root :to => "reservations#new"
  resources :users

  devise_for :users, skip: [:sessions]
  as :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  # def show
  # end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @users = User.where(admin:false)
  end

  # GET /reservations/1/edit
  # def edit
  # end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        #format.html { redirect_to @reservation, notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        # format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    # respond_to do |format|
    #   #format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
    #   #format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:data, :description, :user_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%# link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table class="table">
  <thead>
    <tr>
      <th>Data</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.data %></td>
        <td><%= reservation.description %></td>
        <td><%= reservation.user_id %></td>
        <td><%# link_to 'Show', reservation %></td>
        <td><%# link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%# link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Reserva de Sala', new_reservation_path %>

app/views/reservations/new.html.erb
<h1><%= 'Reserva de Sala' %></h1>

<%= render 'form', reservation: @reservation %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @reservation.data %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reservation.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<%# link_to 'Edit', edit_reservation_path(@reservation) %> |
<%# link_to 'Back', reservations_path %>